### ISSUE TITLE
NPE on freshly git-inited project without any branches

### ISSUE THREAD

**Issue by novotnyr** [novotnyr/git-quickbranches-idea-plugin#1]
Plugin crashes on freshly initialized project.

Reproduce:

1. Create a new IntelliJ project
2. Run `git init`
3. Open the `Git` context submenu when right-clicking on a project.
4. The menu will not open and the NPE will show up.

```
java.lang.NullPointerException
	at com.github.novotnyr.idea.git.BranchListActionGroup.getChildren(BranchListActionGroup.java:60)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$null$3(ActionUpdater.java:82)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.callAction(ActionUpdater.java:106)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$new$4(ActionUpdater.java:82)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$getGroupChildren$20(ActionUpdater.java:220)
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660)
```

**Comment by novotnyr** [comment]
Resolved in v3.
